### ISSUE TITLE
how to set params in command in order to achieve a complete end2end pipeline A

### ISSUE THREAD

**Issue by sherjy** [lescientifik/open_brats2020#11]
Hiiii @lescientifik, thanks a lot for your nice work sharing.
I found pipeline A used 5-fold, swa etc. procedures to achieve a good performance in table 3 of the paper. After checking the paper and codes, I use command like this:
~~~
python3 -m src.train --devices 0 --width 48 --arch EquiUnet --fold 4 --swa --deep_sup
~~~ 
I wonder is this command a correct usage for an end-to-end implementation of pipeline A? I'm concerned that if **--fold 4** here represents a 5-fold execution or just one fold of data for training?

**Comment by lescientifik** [comment]
Hi,

Indeed this will train the network and evaluate on fold 4 only if I remember correctly.

You will have to run the same command with each fold id to perform a complete cross validation (5 fold by default, from 0 to 4 if I remember correctly once again).

**Comment by sherjy** [comment]
Thanks to @lescientifik  for your quick reply! Sorry to bother again bro, so if I have 5 final checkpoints 'model_best.pth' for each fold output, then how to utilize them for validation or test inference?

**Comment by zhangshuang317** [comment]
> Thanks to @lescientifik for your quick reply! Sorry to bother again bro, so if I have 5 final checkpoints 'model_best.pth' for each fold output, then how to utilize them for validation or test inference?

Hello, I encountered the same problem, did you solve it, can you share with me?
