### ISSUE TITLE
inference.py

### ISSUE THREAD

**Issue by H-CODE6** [lescientifik/open_brats2020#13]
Hello, when I run information Py, keep reporting
 usage: inference.py [-h] [--config PATH [PATH ...]] --devices DEVICES
                    [--on {val,train,test}] [--tta] [--seed SEED]

Brats validation and testing dataset inference

optional arguments:
  -h, --help            show this help message and exit
  --config PATH [PATH ...]
                        /media/hkw/hkwdisk/open_brats2020-main/src/20220311_10
                        5344__fold0_EquiUnet_48_batch1_optimranger_ranger_lr0.
                        0001-wd0.0_epochs200_deepsupFalse_fp16_warm0__normgrou
                        p_dropout0.0_warm_restartFalse.yaml
  --devices DEVICES     Set the CUDA_VISIBLE_DEVICES env var from this string
  --on {val,train,test}
  --tta
  --seed SEED

What is the reason for this, or run information Which parameters need to be modified when using py？

**Comment by 18774209212** [comment]
I also encountered this problem, how did you solve it?

**Comment by H-CODE6** [comment]
Sorry, it hasn't been resolved yet.
