### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by SungGae** [lescientifik/open_brats2020#4]
hello.
Thanks to good source
but I have a problem testing this source

`first idx of train 1
first idx of test 0
Val dataset number of batch: 74
Train dataset number of batch: 295
start warm-up now!
Traceback (most recent call last):
  File "C:\anaconda\envs\test1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\anaconda\envs\test1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\윤종학\Desktop\open_brats2020-main\open_brats2020-main\src\train.py", line 471, in <module>
    main(arguments)
  File "C:\Users\윤종학\Desktop\open_brats2020-main\open_brats2020-main\src\train.py", line 242, in main
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer,
UnboundLocalError: local variable 'optimizer' referenced before assignment`

I tried 'pip install e .' but this error 
I'm a beginner so I don't know what's wrong
please help

**Comment by lescientifik** [comment]
Hi,

Looking back at my code, you may have given the optimizer name wrong on the commandline, which cause none of the conditionnal blocks to fire.

Try running the code using "sgd" as the optim argument at the commandline

**Comment by SungGae** [comment]
Thank you for your cooperation. As a result of switching to sgd, I was able to create a model. However, it was not possible to resolve the creation of the yaml file among the first errors, so I did not have a yaml file due to comment processing. Could you please advise on this error as well?

**Comment by lescientifik** [comment]
Without more info it will be hard to move on, sry.
